Repository nelkor/passcryptum, pull requests merged in 2023-12, with the labels that each got.

#183 Move sign out to end of menu
  src/widgets/app-header/components/MenuButton.vue
Labels: refactoring

#181 🔍 Improve Manifest
  .github/workflows/ci.yaml
  index.html
  public/icons/favicon.svg
  public/icons/i192x192.png
  public/icons/i512x512.png
  public/manifest.json
  public/screenshots/login.png
  public/screenshots/service.png
  public/sw.js
  src/widgets/app-header/components/AppHeader.vue
Labels: bug, research and develop, refactoring

#185 🐛 Fix services import
  src/entities/session/model/public.ts
  src/features/storage/components/ImportFromText.vue
Labels: bug

#186 🔖 Release 2.1.3
  .github/workflows/ci.yaml
  index.html
  public/icons/favicon.svg
  public/icons/i192x192.png
  public/icons/i512x512.png
  public/manifest.json
  public/screenshots/login.png
  public/screenshots/service.png
  public/sw.js
  src/entities/session/model/public.ts
  src/features/storage/components/ImportFromText.vue
  src/widgets/app-header/components/AppHeader.vue
  src/widgets/app-header/components/MenuButton.vue
Labels: release
