Repository nelkor/passcryptum, pull requests merged in 2023-03, with the labels that each got.

#15 🐞 Restore the sass-package
  package.json
Labels: bug

#13 :sparkles: Prepare pages
  src/app/components/App.vue
  src/entities/master-password/hooks/master.hook.ts
  src/entities/master-password/index.ts
  src/features/master-password/components/MasterForm.vue
  src/features/master-password/hooks/master-form.hook.ts
  src/features/master-password/index.ts
  src/pages/password-entry/components/PasswordEntry.vue
  src/pages/password-entry/index.ts
  src/pages/work-screen/components/WorkScreen.vue
  src/pages/work-screen/index.ts
Labels: enhancement

#20 :construction: The Master tool
  src/entities/master-password/hooks/master-tool.hook.ts
  src/entities/master-password/hooks/master.hook.ts
  src/entities/master-password/index.ts
  src/entities/master-password/lib/create-master-tool.ts
  src/entities/master-password/types.ts
  src/features/master-password/hooks/master-form.hook.ts
  src/shared/index.ts
  src/shared/lib/hash.ts
  src/shared/lib/text-tools.ts
  tsconfig.app.json
Labels: enhancement

#25 :white_check_mark: Try Vitest
  .husky/pre-commit
  package.json
  src/entities/master-password/test/create-master-tool.spec.ts
Labels: enhancement

#26 🔧 Redundant rule "max-len" in ESLint
  .eslintrc.cjs
Labels: bug

#29 🏷️ Develop a configuration interface
  src/entities/services-config/types.ts
Labels: documentation, enhancement, research and develop

#33 🐛 Typo in entities/master-password/test/create-master-tool.spec.ts
  src/entities/master-password/test/create-master-tool.spec.ts
Labels: bug, good first issue

#32 ✨ Config compression/decompression utils
  src/entities/services-config/lib/compress-config.ts
  src/entities/services-config/lib/decompress-config.ts
  src/entities/services-config/test/compress-config.spec.ts
  src/entities/services-config/test/decompress-config.spec.ts
  src/entities/services-config/test/examples.ts
  src/entities/services-config/types.ts
Labels: enhancement

#36 ♻️ Entry/MasterTool refactoring
  src/app/components/App.vue
  src/entities/master-password/index.ts
  src/entities/master-tool/index.ts
  src/entities/master-tool/lib/create-master-tool.ts
  src/entities/master-tool/model/master-tool.ts
  src/entities/master-tool/test/create-master-tool.spec.ts
  src/entities/master-tool/types.ts
  src/entities/services-config/index.ts
  src/entities/services-config/lib/create-empty-config.ts
  src/entities/services-config/model/service-config.ts
  src/features/entry/actions/enter.ts
  src/features/entry/actions/exit.ts
  src/features/entry/components/MasterForm.vue
  src/features/entry/hooks/master-form.ts
  src/features/entry/index.ts
  src/pages/password-entry/components/PasswordEntry.vue
  src/pages/work-screen/components/WorkScreen.vue
Labels: bug

#34 ✨ Create a password generation function
  src/shared/lib/generate-password.ts
  src/shared/test/generate-password.spec.ts
Labels: enhancement

#40 ✨ Symmetric encryption/decryption
  src/entities/master-tool/lib/create-master-tool.ts
  src/shared/index.ts
  src/shared/lib/aes.ts
  src/shared/lib/text-tools.ts
  src/shared/test/aes.spec.ts
Labels: enhancement

#41 ✨ Configuration widget
  src/entities/master-tool/index.ts
  src/entities/master-tool/lib/decrypt-hex.ts
  src/entities/master-tool/model/master-tool.ts
  src/entities/services-config/index.ts
  src/entities/services-config/model/service-config.ts
  src/features/configuration-export/components/ConfigEncryptedCopy.vue
  src/features/configuration-export/components/ConfigFileExport.vue
  src/features/configuration-export/components/ConfigRawJsonCopy.vue
  src/features/configuration-export/hooks/clipboard-copy.ts
  src/features/configuration-export/hooks/file-export.ts
  src/features/configuration-export/index.ts
  src/features/configuration-export/lib/get-encrypted-config.ts
  src/features/configuration-import/components/ConfigFileImport.vue
  src/features/configuration-import/components/ConfigTextImport.vue
  src/features/configuration-import/components/DeleteConfig.vue
  src/features/configuration-import/hooks/delete-config.ts
  src/features/configuration-import/hooks/file-import.ts
  src/features/configuration-import/hooks/text-import.ts
  src/features/configuration-import/index.ts
  src/features/configuration-import/lib/import-text.ts
  src/features/configuration-import/lib/parse-config.ts
  src/features/configuration-import/lib/set-configuration.ts
  src/features/entry/actions/enter.ts
  src/pages/work-screen/components/WorkScreen.vue
  src/widgets/configuration-panel/components/ConfigurationPanel.vue
  src/widgets/configuration-panel/index.scss
  src/widgets/configuration-panel/index.ts
Labels: enhancement

#43 ✨ List of custom services
  src/entities/services-config/index.ts
  src/entities/services-config/lib/create-empty-config.ts
  src/entities/services-config/lib/creation-tools.ts
  src/entities/services-config/lib/custom-services.ts
  src/entities/services-config/model/service-config.ts
  src/entities/services-config/types.ts
  src/features/add-custom-service/components/AddCustomService.vue
  src/features/add-custom-service/hooks/add-custom-service.ts
  src/features/add-custom-service/index.ts
  src/features/configuration-export/hooks/clipboard-copy.ts
  src/features/configuration-export/lib/get-encrypted-config.ts
  src/features/configuration-import/lib/set-configuration.ts
  src/features/save-configuration/components/SaveCancelConfig.vue
  src/features/save-configuration/hooks/save-changes.ts
  src/features/save-configuration/index.ts
  src/features/service-management/components/CustomService.vue
  src/features/service-management/components/ServicePreferences.vue
  src/features/service-management/hooks/custom-service.ts
  src/features/service-management/hooks/service-preferences.ts
  src/features/service-management/index.scss
  src/features/service-management/index.ts
  src/pages/work-screen/components/WorkScreen.vue
  src/shared/index.ts
  src/shared/ui/copy-button/CopyButton.vue
  src/shared/ui/index.ts
  src/shared/ui/password-length-group/PasswordLengthGroup.vue
  src/widgets/configuration-panel/components/ConfigurationPanel.vue
  src/widgets/custom-services/components/CustomServicesList.vue
  src/widgets/custom-services/index.scss
  src/widgets/custom-services/index.ts
Labels: enhancement
