Repository nelkor/passcryptum, pull requests merged in 2023-05, with the labels that each got.

#74 ✨ Focus master-password input
  src/features/entry/components/MasterForm.vue
  src/features/entry/hooks/master-form.ts
Labels: enhancement

#72 📝 Describe the password generation algorithm
  docs/en/password-generation-algorithm.md
  docs/ru/password-generation-algorithm.md
Labels: documentation

#78 🐞 Letter appears after hotkey on macbook
  src/features/services-filter/hooks/hotkey-focus.ts
Labels: bug

#76 📝 README.md
  LICENSE
  README.md
Labels: documentation

#79 Pre-release fix
  README.md
Labels: release

#82 ✨ Aside window
  .github/workflows/ci.yaml
  .stylelintrc
  index.html
  src/app/style/helpers.scss
  src/app/style/index.scss
  src/app/style/normalize.scss
  src/dom/index.ts
  src/entities/aside-window/components/AppAside.vue
  src/entities/aside-window/hooks/app-aside.ts
  src/entities/aside-window/index.scss
  src/entities/aside-window/index.ts
  src/entities/aside-window/model/aside-window.ts
  src/entities/aside-window/types.ts
  src/features/configuration-import/components/ConfigTextImport.vue
  src/pages/work-screen/components/WorkScreen.vue
  src/widgets/app-header/components/AppHeader.vue
  src/widgets/app-header/components/ConfigurationAside.vue
  src/widgets/app-header/hooks/app-header.ts
  src/widgets/app-header/index.ts
  src/widgets/configuration-panel/index.scss
  src/widgets/configuration-panel/index.ts
  src/widgets/short-hash/components/ShortHash.vue
  src/widgets/short-hash/index.ts
Labels: enhancement

#89 🐞 Build for standalone
  README.md
  package.json
  vite.config.ts
Labels: bug

#87 ♻️ Services list
  src/app/style/normalize.scss
  src/entities/aside-window/components/AppAside.vue
  src/entities/aside-window/model/aside-window.ts
  src/entities/aside-window/types.ts
  src/entities/services-config/model/service-config.ts
  src/features/entry/actions/enter.ts
  src/features/service-management/components/LoginAdder.vue
  src/features/service-management/components/LoginItem.vue
  src/features/service-management/components/LoginsList.vue
  src/features/service-management/components/ServiceDetails.vue
  src/features/service-management/components/ServiceItem.vue
  src/features/service-management/hooks/login-adder.ts
  src/features/service-management/hooks/login-item.ts
  src/features/service-management/hooks/service-adder.ts
  src/features/service-management/hooks/service-deleting.ts
  src/features/service-management/hooks/service-details.ts
  src/features/service-management/hooks/service-item.ts
  src/features/service-management/index.scss
  src/features/service-management/index.ts
  src/features/service-management/style/login.scss
  src/features/service-management/style/service.scss
  src/widgets/app-header/components/ConfigurationAside.vue
  src/widgets/services-header/components/ServicesHeader.vue
  src/widgets/services-header/hooks/service-header.ts
Labels: enhancement, refactoring

#91 💄 Connect font
  src/app/style/index.scss
  src/app/style/typography.scss
Labels: beauty

#93 💄 Work screen wrapper
  src/entities/aside-window/index.scss
  src/pages/work-screen/components/WorkScreen.vue
  src/pages/work-screen/index.scss
  src/pages/work-screen/index.ts
  src/pages/work-screen/style/work-screen.scss
  src/pages/work-screen/style/work-wrapper.scss
Labels: beauty

#95 💄 Work header
  src/pages/work-screen/components/WorkScreen.vue
  src/shared/icons/IconBurger.vue
  src/shared/icons/IconExit.vue
  src/shared/icons/index.ts
  src/shared/index.ts
  src/widgets/app-header/components/AppHeader.vue
  src/widgets/app-header/index.ts
  src/widgets/work-header/components/ConfigurationAside.vue
  src/widgets/work-header/components/WorkHeader.vue
  src/widgets/work-header/hooks/app-header.ts
  src/widgets/work-header/index.scss
  src/widgets/work-header/index.ts
  src/widgets/work-header/style/work-header.scss
Labels: beauty

#97 💄 Services header
  src/features/services-filter/components/ServicesFilter.vue
  src/features/services-filter/index.scss
  src/features/services-filter/index.ts
  src/widgets/services-header/components/ServicesHeader.vue
  src/widgets/services-header/index.scss
  src/widgets/services-header/index.ts
Labels: beauty

#99 💄 Aside header
  src/entities/aside-window/components/AppAside.vue
  src/entities/aside-window/index.scss
  src/features/save-configuration/components/SaveCancelConfig.vue
  src/shared/icons/IconCross.vue
  src/shared/icons/index.ts
  src/widgets/work-header/components/ConfigurationAside.vue
Labels: beauty

#101 💄 Finish basic styles
  src/app/style/helpers.scss
  src/app/style/normalize.scss
  src/app/style/typography.scss
  src/entities/aside-window/components/AppAside.vue
  src/entities/aside-window/index.scss
  src/features/configuration-export/components/ConfigFileExport.vue
  src/features/configuration-import/components/ConfigFileImport.vue
  src/features/configuration-import/components/ConfigTextImport.vue
  src/features/configuration-import/components/DeleteConfig.vue
  src/features/configuration-import/index.scss
  src/features/configuration-import/index.ts
  src/features/save-configuration/components/SaveCancelConfig.vue
  src/features/service-management/components/LoginItem.vue
  src/features/service-management/components/ServiceDetails.vue
  src/features/service-management/components/ServiceItem.vue
  src/features/service-management/components/ServicePreferences.vue
  src/features/service-management/hooks/login-item.ts
  src/features/service-management/hooks/service-preferences.ts
  src/features/service-management/index.scss
  src/features/service-management/index.ts
  src/features/service-management/style/login-item.scss
  src/features/service-management/style/logins-list.scss
  src/features/service-management/style/password-length.scss
  src/features/service-management/style/service-item.scss
  src/features/service-management/style/service-preferences.scss
  src/features/services-filter/components/ServicesFilter.vue
  src/features/services-filter/index.scss
  src/features/services-filter/index.ts
  src/shared/icons/IconDetails.vue
  src/shared/icons/IconKey.vue
  src/shared/icons/IconUser.vue
  src/shared/icons/index.ts
  src/widgets/services-header/components/ServicesHeader.vue
  src/widgets/services-header/index.scss
  src/widgets/services-list/components/ServicesList.vue
  src/widgets/services-list/index.scss
  src/widgets/services-list/index.ts
  src/widgets/work-header/components/ConfigurationAside.vue
  src/widgets/work-header/components/WorkHeader.vue
  src/widgets/work-header/hooks/app-header.ts
  src/widgets/work-header/index.scss
  src/widgets/work-header/style/configuration-aside.scss
  src/widgets/work-header/style/work-header.scss
Labels: beauty

#109 ♻️ Remake the password entry
  src/features/entry/components/MasterForm.vue
  src/features/entry/index.scss
  src/features/entry/index.ts
  src/pages/password-entry/components/PasswordEntry.vue
  src/pages/password-entry/index.scss
  src/pages/password-entry/index.ts
  src/widgets/app-info/components/AppInfo.vue
  src/widgets/app-info/components/AppInfoLink.vue
  src/widgets/app-info/index.scss
  src/widgets/app-info/index.ts
Labels: beauty

#111 ✨ Trim names
  src/features/service-management/hooks/service-details.ts
  src/widgets/services-header/hooks/service-header.ts
Labels: bug, enhancement

#115 📦 Update package versions
  package.json
  tsconfig.app.json
  tsconfig.config.json
Labels: enhancement

#110 🐞 Copy doesn't work in Safari
  src/shared/ui/copy-button/CopyButton.vue
Labels: bug

#107 ✨ Validate config on import
  src/features/configuration-import/lib/check-compressed.ts
  src/features/configuration-import/lib/parse-config.ts
  src/features/configuration-import/test/check-compressed.spec.ts
Labels: bug, enhancement, research and develop

#123 🐞 Normalize input border-radius
  src/app/style/normalize.scss
Labels: bug, beauty

#120 :bug: Fix bug in service name
  src/app/style/helpers.scss
  src/entities/aside-window/index.scss
Labels: bug

#126 :bookmark: Release 1.1.1
  src/app/style/helpers.scss
  src/app/style/normalize.scss
  src/entities/aside-window/index.scss
Labels: release

#128 ⏪ Rollback dependency versions
  package.json
  src/features/service-management/components/ServiceDetails.vue
  tsconfig.app.json
  tsconfig.config.json
Labels: bug, research and develop, refactoring
