Repository nelkor/passcryptum, pull requests merged in 2023-04, with the labels that each got.

#47 ✨ Display a short hash on the working screen
  src/pages/work-screen/components/WorkScreen.vue
  src/widgets/short-hash/components/ShortHash.vue
  src/widgets/short-hash/index.ts
Labels: enhancement

#48 ✨ List of logins
  src/entities/services-config/lib/compress-config.ts
  src/entities/services-config/lib/creation-tools.ts
  src/entities/services-config/lib/custom-services.ts
  src/entities/services-config/lib/decompress-config.ts
  src/entities/services-config/types.ts
  src/features/service-management/components/AddLoginToCustomService.vue
  src/features/service-management/components/CustomService.vue
  src/features/service-management/components/LoginItem.vue
  src/features/service-management/components/LoginsList.vue
  src/features/service-management/components/ServicePreferences.vue
  src/features/service-management/hooks/add-login-to-custom-service.ts
  src/features/service-management/hooks/login-item.ts
  src/features/service-management/index.scss
  src/features/service-management/lib/get-password-of-login.ts
  src/shared/index.ts
  src/shared/lib/charset.ts
  src/shared/lib/password-length.ts
  src/shared/test/generate-password.spec.ts
  src/shared/ui/copy-button/CopyButton.vue
  src/shared/ui/password-length-group/PasswordLengthGroup.vue
Labels: enhancement

#52 ♻️ Services refactoring
  src/entities/services-config/index.ts
  src/entities/services-config/lib/compress-config.ts
  src/entities/services-config/lib/creation-tools.ts
  src/entities/services-config/lib/custom-services.ts
  src/entities/services-config/lib/decompress-config.ts
  src/entities/services-config/model/service-config.ts
  src/entities/services-config/test/examples.ts
  src/entities/services-config/types.ts
  src/features/add-custom-service/hooks/add-custom-service.ts
  src/features/add-custom-service/index.ts
  src/features/service-management/components/AddLoginToCustomService.vue
  src/features/service-management/components/CustomService.vue
  src/features/service-management/components/LoginAdder.vue
  src/features/service-management/components/LoginItem.vue
  src/features/service-management/components/LoginsList.vue
  src/features/service-management/components/ServiceAdder.vue
  src/features/service-management/components/ServiceItem.vue
  src/features/service-management/components/ServicePreferences.vue
  src/features/service-management/hooks/custom-service.ts
  src/features/service-management/hooks/login-adder.ts
  src/features/service-management/hooks/login-item.ts
  src/features/service-management/hooks/service-adder.ts
  src/features/service-management/hooks/service-deleting.ts
  src/features/service-management/index.scss
  src/features/service-management/index.ts
  src/features/service-management/providers/service.ts
  src/pages/work-screen/components/WorkScreen.vue
  src/shared/hooks/provide.ts
  src/shared/index.ts
  src/widgets/custom-services/components/CustomServicesList.vue
  src/widgets/custom-services/index.ts
  src/widgets/services-list/components/ServicesList.vue
  src/widgets/services-list/index.scss
  src/widgets/services-list/index.ts
Labels: enhancement

#58 Github workflow added
  .github/workflows/ci.yaml
  package.json
Labels: enhancement, good first issue

#59 🔧 Get rid of husky
  .husky/pre-commit
  package.json
Labels: enhancement

#60 ✨ Add option to delete login
  src/entities/services-config/model/service-config.ts
  src/features/service-management/components/LoginItem.vue
  src/features/service-management/hooks/login-item.ts
Labels: enhancement

#63 ✨ Password generator entity
  src/entities/master-tool/lib/create-master-tool.ts
  src/entities/master-tool/types.ts
  src/entities/password-generator/index.ts
  src/entities/password-generator/lib/charset.ts
  src/entities/password-generator/lib/create-calculator.ts
  src/entities/password-generator/lib/generate-password.ts
  src/entities/password-generator/model/password-generator.ts
  src/entities/password-generator/test/generate-password.spec.ts
  src/entities/password-generator/test/passwords-calculator.spec.ts
  src/entities/password-generator/types.ts
  src/features/entry/actions/enter.ts
  src/features/entry/actions/exit.ts
  src/features/service-management/lib/get-password-of-login.ts
  src/shared/index.ts
Labels: enhancement, research and develop

#62 ♻️ Use CopyButton in ConfigurationPanel
  src/features/configuration-export/components/ConfigEncryptedCopy.vue
  src/features/configuration-export/components/ConfigRawJsonCopy.vue
  src/features/configuration-export/hooks/clipboard-copy.ts
  src/features/configuration-export/index.ts
  src/features/configuration-export/lib/get-config-text.ts
  src/shared/ui/copy-button/CopyButton.vue
  src/widgets/configuration-panel/components/ConfigurationPanel.vue
Labels: enhancement

#61 💄 Adapt layout to small screens
  .stylelintrc
  src/app/style/normalize.scss
  src/features/service-management/components/LoginItem.vue
  src/features/service-management/components/ServiceItem.vue
  src/features/service-management/index.scss
  src/features/service-management/style/login.scss
  src/features/service-management/style/service.scss
Labels: bug, enhancement

#68 ♻️ Replace some alerts with confirms
  src/features/configuration-import/hooks/delete-config.ts
  src/features/entry/actions/exit.ts
  src/features/service-management/hooks/service-deleting.ts
Labels: research and develop, refactoring

#69 ♻️ Supplement config on import
  package.json
  src/features/configuration-import/lib/merge-configurations.ts
  src/features/configuration-import/lib/set-configuration.ts
  src/features/configuration-import/test/examples.ts
  src/features/configuration-import/test/merge-configurations.spec.ts
Labels: enhancement

#70 ♻️ Migrate interaction with password length
  src/features/service-management/components/ServicePreferences.vue
  src/features/service-management/lib/get-password-of-login.ts
  src/features/service-management/lib/password-length.ts
  src/shared/index.ts
  src/shared/ui/index.ts
  src/shared/ui/password-length-group/PasswordLengthGroup.vue
Labels: refactoring

#71 ✨ Filter-search for services by name
  src/features/service-management/components/ServiceAdder.vue
  src/features/services-filter/components/ServicesFilter.vue
  src/features/services-filter/hooks/hotkey-focus.ts
  src/features/services-filter/index.ts
  src/features/services-filter/model/services-filter.ts
  src/shared/index.ts
  src/shared/lib/element-ref.ts
  src/widgets/services-list/components/ServicesList.vue
  src/widgets/services-list/index.scss
Labels: enhancement
