Repository nelkor/passcryptum, pull requests merged in 2023-06, with the labels that each got.

#121 :wrench: Add PWA
  .eslintrc.cjs
  package.json
  public/sw.js
  src/main.ts
Labels: enhancement, research and develop, refactoring

#133 ✨ Deny WebSocket
  src/main.ts
Labels: enhancement

#132 ♻️ Move favicon to index.html
  index.html
  public/favicon.svg
Labels: refactoring

#135 🐞 Index not cached after first run
  public/sw.js
Labels: bug, enhancement

#137 ✨ Add a link to the Telegram channel to the main page
  src/main.ts
  src/widgets/app-info/components/AppInfo.vue
  src/widgets/app-info/components/AppInfoLink.vue
  src/widgets/app-info/components/GitHubLink.vue
Labels: enhancement, beauty

#139 ⬆️ Upgrade dependencies
  .eslintrc
  .eslintrc.cjs
  .github/workflows/ci.yaml
  .prettierrc
  .stylelintrc
  env.d.ts
  package.json
  src/app/style/helpers.scss
  src/entities/aside-window/index.scss
  src/entities/master-tool/test/create-master-tool.spec.ts
  src/entities/password-generator/test/generate-password.spec.ts
  src/entities/password-generator/test/passwords-calculator.spec.ts
  src/features/service-management/style/login-item.scss
  src/features/service-management/style/password-length.scss
  src/pages/password-entry/index.scss
  src/pages/work-screen/style/work-screen.scss
  src/pages/work-screen/style/work-wrapper.scss
  src/shared/test/aes.spec.ts
  src/widgets/app-info/index.scss
  src/widgets/services-header/index.scss
  tsconfig.app.json
  tsconfig.config.json
  tsconfig.json
  tsconfig.vitest.json
  vite.config.ts
  vitest.config.ts
Labels: refactoring

#140 :bookmark: Set version
  public/sw.js
Labels: release

#129 ✨ Service Worker
  .eslintrc
  .eslintrc.cjs
  .github/workflows/ci.yaml
  .prettierrc
  .stylelintrc
  env.d.ts
  index.html
  package.json
  public/favicon.svg
  public/sw.js
  src/app/style/helpers.scss
  src/entities/aside-window/index.scss
  src/entities/master-tool/test/create-master-tool.spec.ts
  src/entities/password-generator/test/generate-password.spec.ts
  src/entities/password-generator/test/passwords-calculator.spec.ts
  src/features/service-management/components/ServiceDetails.vue
  src/features/service-management/style/login-item.scss
  src/features/service-management/style/password-length.scss
  src/main.ts
  src/pages/password-entry/index.scss
  src/pages/work-screen/style/work-screen.scss
  src/pages/work-screen/style/work-wrapper.scss
  src/shared/test/aes.spec.ts
  src/widgets/app-info/components/AppInfo.vue
  src/widgets/app-info/components/AppInfoLink.vue
  src/widgets/app-info/components/GitHubLink.vue
  src/widgets/app-info/index.scss
  src/widgets/services-header/index.scss
  tsconfig.app.json
  tsconfig.config.json
  tsconfig.json
  tsconfig.vitest.json
  vite.config.ts
  vitest.config.ts
Labels: enhancement

#142 :ambulance: Fix aside on small screens
  src/entities/aside-window/index.scss
Labels: bug, release

#143 🔖 Release 1.2.1
  public/sw.js
Labels: release

#144 🔖 Hotfix v1.2.2: media notation
  .stylelintrc
  public/sw.js
  src/entities/aside-window/index.scss
  src/pages/password-entry/index.scss
  src/pages/work-screen/style/work-screen.scss
  src/pages/work-screen/style/work-wrapper.scss
  src/widgets/services-header/index.scss
Labels: bug, release
